name: system_auth
description: "system authentification"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  leak_tracker: ^10.0.4
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  lottie: ^3.1.2
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  skeleton_text: ^3.0.1
  # flutter_tts: ^4.0.2
  audioplayers: ^5.2.1
  connectivity_plus: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  leak_tracker_flutter_testing: ^3.0.3
  lints: ^4.0.0
  test_api: 0.7.0
  vm_service: 14.2.1
  loading_animation_widget: ^1.2.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/soma1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lexus
      fonts:
        - asset: Lexend_Deca/lex1.ttf
        # - asset: lexus/YourFontFile-Bold.ttf
          # weight: 700
        # - asset: lexus/YourFontFile-Italic.ttf
        #   style: italic
